development:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: vendomitelefono
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: 
  pool: 5
  username: 
  password: 

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: 
  pool: 5
  username: 
  password: 
